Blog_Web_Application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),

]
if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views


app_name = 'blog'
urlpatterns = [
    path('',	views.post_list,	name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
	def	get_queryset(self):
		return	super(PublishedManager
						,self).get_queryset()\
								.filter(status='published')


class Post(models.Model):
	STATUS_CHOICES = (
		('draft',	'Draft'),
		('published',	'Published'),
	)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	objects = models.Manager()  # The	default	manager.
	published = PublishedManager()  # Our	custom	manager.

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment	by	{}	on	{}'.format(self.name,	self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(required=True,widget=forms.TextInput(attrs={'id':'contact_name','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'id':'contact_email','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))
    to = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'id':'contact_email','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))
    comments = forms.CharField(required=False, widget=forms.TextInput(attrs={'id':'contact_message','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))


class CommentForm(forms.ModelForm):
    name = forms.CharField(required=True,widget=forms.TextInput(attrs={'id':'contact_name','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'id':'contact_email','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))
    body = forms.CharField(required=False, widget=forms.TextInput(attrs={'id':'contact_message','class':'form-control rounded-0 border-top-0 border-right-0 border-left-0'}))

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
# Create your views here.
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage,\
                                        PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.conf import settings


def post_share(request,	post_id):
    # Retrieve	post	by	id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was	submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form	fields	passed	validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({})recommends	you	reading	"{}"'.format(cd['name'],	cd['email'],	post.title)
            message = 'Read	"{}"	at	{}\n\n{}\'s	comments:{}'.format(post.title,	post_url,	cd['name'],	cd['comments'])
            send_mail(subject, message, 'pranalimahajan2510@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,	'blog/post/share.html',	{'post': post, 'form': form,'sent': sent})


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list,	3)
    # 3 posts	in	each	page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If	page	is	out	of	range	deliver	last	page	of	results
        posts = paginator.page(1)
    except EmptyPage:
        # If	page	is	out	of	range	deliver	last	page	of	results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page':	page, 'posts':	posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,	slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
# List	of	active	comments	for	this	post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A	comment	was	posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create	Comment	object	but	don't	save	to	database	yet
            new_comment = comment_form.save(commit=False)
            # Assign	the	current	post	to	the	comment
            new_comment.post = post
            # Save	the	comment	to	the	database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post,'comments': comments, 'new_comment': new_comment, 'comment_form':	comment_form})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

templates/blog/base.html
{%	load	static	%}
<html lang="en">
<head>
	    <title>{%	block	title	%}{%	endblock	%}</title>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}" />

</head>
<!--
Sided Template
https://templatemo.com/tm-527-sided
-->
<body>
<div class="columns-bg">
    <!-- Logo & Intro -->
    <section id="logo" class="tm-section-logo">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 offset-sm-0 col-md-6 offset-md-6">
                    <div class="tm-site-name-container">
                        <div class="tm-site-name-container-inner">
                            <h1 class="text-uppercase tm-text-primary tm-site-name">
                                My Blog                  </h1>
                            <p class="tm-text-primary tm-site-description">
                                Just for you
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Beautiful Rollovers -->


    <div	id="content">
        {%	block	content	%}



        {%	endblock	%}
    </div>
    <section id="outro">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="tm-section-text-container-5 tm-text-white">
                        <p>
                           “Blogging is to writing what extreme sports are to athletics: more free-form, more accident-prone, less formal, more alive. It is, in many ways, writing out loud.”
                        </p>
                        <i>“Blogging is just writing — writing using a particularly efficient type of publishing technology.”
                        </i>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="tm-section-text-container-6">
                        <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-facebook-f"></i>
                  </span>
                        </a>
                        <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-twitter"></i>
                  </span>
                        </a>
                        <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-instagram"></i>
                  </span>
                        </a>
                        <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-google-plus-g"></i>
                  </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <footer class="col-sm-12 col-md-6 offset-md-6 px-md-0">
                    <p class="tm-copyright-text mb-0 tm-text-primary">
                        Copyright &copy; 2019 Company Name - Design: <a rel="nofollow" href="#">TemplateMo</a>
                    </p>
                </footer>
            </div>
        </div>
    </section>
</div>
<!-- /.columns-bg -->
</body>
</html>

templates/blog/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="css/all.min.css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/templatemo-style.css" />
    <title>Sided Bootstrap 4 Theme</title>
  </head>
<!--
Sided Template
https://templatemo.com/tm-527-sided
-->
  <body>
    <div class="columns-bg">
      <!-- Logo & Intro -->
      <section id="logo" class="tm-section-logo">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12 offset-sm-0 col-md-6 offset-md-6">
              <div class="tm-site-name-container">
                <div class="tm-site-name-container-inner">
                  <h1 class="text-uppercase tm-text-primary tm-site-name">
                    Sided
                  </h1>
                  <p class="tm-text-primary tm-site-description">
                    new theme just for you
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Intro -->
      <section id="intro" class="tm-p-1-section-1">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6">
              <div class="tm-section-text-container">
                <i class="tm-text-white">
                  <p class="mb-0">
                    Nullam eget dignissim orci. Donec tincidunt blandit libero iaculis fermentum. Aliquam erat volutpat. Interger suscipit aliquam augue ac rutrum. Phasellus sit amet erat id sapien efficitur euismod.</p>
                </i>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Our Place -->
      <section id="our_place">
        <div class="container-fluid">
          <div class="row">
            <div
              class="col-md-12 col-lg-6 tm-section-image-container tm-img-left-container"
            >
              <img src="img/forty_image_01.jpg" alt="Image" class="img-fluid" />
            </div>
            <div class="col-md-12 col-lg-6">
              <div class="tm-section-text-container-2">
                <h2
                  class="tm-text-primary tm-section-title-mb tm-sm-bg-white-alpha"
                >
                  Our Place
                </h2>
                <div class="tm-text-gray">
                  <p class="mb-4">
                  	Sided Bootstrap v4.2.1 template has 3 HTML pages. <a href="index.html">Index</a>, <a href="page-2.html">Page 2</a> and <a href="page-3.html">Page 3</a>.
                    You may share this Sided template or <a rel="nofollow" href="https://www.facebook.com/templatemo">our templatemo page</a> to your friends. Pellentesque commodo malesuada est.
                    </p>
                  <p class="mb-0">
                    Suspendisse porttitor sollicitudin nisi et bibendum. Donec
                    ac semper ante, non sagittis sapien. Duis hendrerit tellus
                    sit amet cursus euismod.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Fusce, Section 4 -->
      <section id="section_4" class="tm-section-4">
        <div class="container-fluid">
          <div class="row flex-column-reverse flex-lg-row">
            <div class="col-md-12 col-lg-6 tm-text-left-container">
              <div class="tm-section-text-container-3 tm-bg-white-alpha h-100">
                <h2 class="tm-text-accent tm-section-title-mb">
                  Fusce a porttitor augue
                </h2>
                <p class="mb-0">
                  Quisque rutrum dapibus odio vitae tincidunt. Etiam
                  sollicitudin augue non porta interdum. Pellentesque placerat
                  orci at libero ornare, nec viverra justo lobortis. Phasellus
                  venenatis eros non.
                </p>
              </div>
            </div>
            <div
              class="col-md-12 col-lg-6 tm-section-image-container tm-img-right-container"
            >
              <img
                src="img/forty_image_02.jpg"
                alt="Image"
                class="img-fluid tm-img-right"
              />
            </div>
          </div>
        </div>
      </section>

      <!-- Beautiful Rollovers -->
      <section id="gallery">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 tm-section-title-mb tm-gallery-title-col">
              <h2 class="tm-section-title-2">Beautiful Rollovers</h2>
              <hr class="tm-section-title-underline" />
            </div>

            <div class="col-12">
              <div class="grid">
                <figure class="effect-duke mb-3">
                  <img
                    src="img/forty_image_11.jpg"
                    alt="Image"
                    class="img-fluid"
                  />
                  <figcaption>
                    <h2>Messy <span>Duke</span></h2>
                    <p>When he looks at the sky, he feels to run.</p>
                    <a href="#">View more</a>
                  </figcaption>
                </figure>
                <figure class="effect-duke">
                  <img
                    src="img/forty_image_12.jpg"
                    alt="Image"
                    class="img-fluid"
                  />
                  <figcaption>
                    <h2>Messy <span>Duke</span></h2>
                    <p>When he looks at the sky, he feels to run.</p>
                    <a href="page-2.html">View more</a>
                  </figcaption>
                </figure>
                <figure class="effect-duke mb-3">
                  <img
                    src="img/forty_image_13.jpg"
                    alt="Image"
                    class="img-fluid"
                  />
                  <figcaption>
                    <h2>Messy <span>Duke</span></h2>
                    <p>When he looks at the sky, he feels to run.</p>
                    <a href="#">View more</a>
                  </figcaption>
                </figure>
                <figure class="effect-duke">
                  <img
                    src="img/forty_image_14.jpg"
                    alt="Image"
                    class="img-fluid"
                  />
                  <figcaption>
                    <h2>Messy <span>Duke</span></h2>
                    <p>When he looks at the sky, he feels to run.</p>
                    <a href="#">View more</a>
                  </figcaption>
                </figure>
              </div>
            </div>

            <div class="col-md-6 tm-section-col-4">
              <div class="tm-section-text-container-4">
                <p class="tm-text-secondary mb-0">
                  Description text for beautiful rollovers using text color code
                  #999 for this line. Quisque pharetra mauris in libero vaius
                  tristique.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Contact -->
      <section id="contact" class="tm-section-contact">
        <div class="row tm-contact-section">
          <div class="col-md-6 px-0">
            <div class="tm-bg-white-alpha tm-contact-left">
              <div class="media mb-5">
                <a href="#" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-phone tm-contact-icon tm-phone-icon"></i>
                    </span>
                  </span>
                  <span class="media-body"> 010-020-0340 </span>
                </a>
              </div>
              <div class="media mb-5">
                <a href="mailto:" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-envelope tm-contact-icon"></i>
                    </span>
                  </span>
                  <span class="media-body"> info@company.com </span>
                </a>
              </div>
              <div class="media">
                <a href="" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-map-marker-alt tm-contact-icon"></i>
                    </span>
                  </span>
                  <span class="media-body">
                    6120 Suspendisse ultricies<br />Scelerisque tellus, ID
                    10260<br />Magna aliquet porttitor
                  </span>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-6 px-0">
            <div class="tm-contact-form-container">
              <form action="index.html" method="POST" class="tm-contact-form">
                <div class="form-group">
                  <input
                    type="text"
                    id="contact_name"
                    name="contact_name"
                    class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                    placeholder="Your Name"
                    required
                  />
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    id="contact_email"
                    name="contact_email"
                    class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                    placeholder="Email"
                    required
                  />
                </div>
                <div class="form-group">
                  <textarea
                    rows="4"
                    id="contact_message"
                    name="contact_message"
                    class="form-control rounded-0 border-top-0 border-right-0 border-left-0"
                    placeholder="Message"
                    required
                  ></textarea>
                </div>
                <div class="text-right">
                  <button type="submit" class="btn tm-btn-submit rounded-0">
                    Send
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>

      <section id="outro">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              <div class="tm-section-text-container-5 tm-text-white">
                <p>
                  Fusce a porttitor augue. Phasellus nec faucibus erat, vitae
                  sagittis arcu. Quisque viverra dui purus, at rutrum nibh
                  suscipit ut.
                </p>
                <i
                  >&ldquo;Lorem ipsum dolor sit amet, consectetur adipiscing
                  elit. Duis cursus ac mauris maximus auctor.&rdquo;</i
                >
              </div>
            </div>
            <div class="col-sm-12 col-md-6">
              <div class="tm-section-text-container-6">
                <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-facebook-f"></i>
                  </span>
                </a>
                <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-twitter"></i>
                  </span>
                </a>
                <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-instagram"></i>
                  </span>
                </a>
                <a class="tm-social-icon-container">
                  <span class="tm-social-icon-container-inner">
                    <i class="fab fa-google-plus-g"></i>
                  </span>
                </a>
              </div>
            </div>
          </div>
          <div class="row">
            <footer class="col-sm-12 col-md-6 offset-md-6 px-md-0">
              <p class="tm-copyright-text mb-0 tm-text-primary">
                Copyright &copy; 2019 Company Name

                - Design: <a rel="nofollow" href="https://www.facebook.com/templatemo">TemplateMo</a>
              </p>
            </footer>
          </div>
        </div>
      </section>
    </div>
    <!-- /.columns-bg -->
  </body>
</html>

templates/blog/post/detail.html
{%	extends	"blog/base.html"	%}
{%	load	static	%}

{%	block	title	%}{{	post.title	}}{%	endblock	%}
{%	block	content	%}
<section id="section_1" class="tm-p-2-section-1 tm-sm-bg-blue">
    <div class="container-fluid">
        <div class="row flex-column-reverse flex-lg-row">
            <div class="col-md-12 col-lg-6 tm-text-left-container">
                <div class="tm-section-text-container-3 tm-bg-white-alpha h-100">
                    <h2 class="tm-section-title-mb">{{	post.title	}}</h2>
                    <p	class="date">Published	{{	post.publish	}}	by	{{	post.author	}}</p>
                    <hr class="tm-hr-mb" />
                    <p class="tm-p-mb">{{	post.body|linebreaks	}}</p>
                    <div class="text-right">
                        <p>
                            <a	class="btn btn-primary" href="{%	url	"blog:post_share"	post.id	%}"> Share	this	post</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 tm-section-image-container tm-img-right-container">
                <img src="{% static 'img/forty_image_21.jpg' %}" alt="Image" class="img-fluid tm-img-right"/>
            </div>
        </div>
    </div>
</section>



<section id="section_3" class="tm-section-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="tm-section-text-container-7 tm-bg-dark-gray">
                    <h2 class="tm-section-title-mb tm-text-primary-bright">
                        {%	with	comments.count	as	total_comments	%}{{total_comments	}}	comment{{	total_comments|pluralize	}}
                        {%	endwith	%}
                    </h2>
                    <hr class="tm-hr-mb tm-hr-primary-bright tm-section-underline ml-0"/>
                    <p class="tm-p-mb">
                        {%	for	comment	in	comments	%}
                        <div	class="comment">
                        Comment	{{	forloop.counter	}}	by	{{	comment.name	}} {{	comment.created	}} {{	comment.body|linebreaks	}}
                        </div>
                        {%	empty	%}
                     There	are	no	comments	yet.
                     {%	endfor	%}
                    {%	if	new_comment	%}
                    <h2>Your	comment	has	been	added.</h2>
                    {%	else	%}
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Contact -->
<div id="contact" class="tm-section-contact">
    <div class="row tm-contact-section">
        <div class="col-md-6 px-0">

            <div class="tm-bg-white-alpha tm-contact-left">
                <div class="media mb-5">
                    <a href="#" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-phone tm-contact-icon tm-phone-icon"></i>
                    </span>

                  </span>
                        <span class="media-body"> 010-020-0340 </span>
                    </a>
                </div>
                <div class="media mb-5">
                    <a href="mailto:" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-envelope tm-contact-icon"></i>
                    </span>
                  </span>
                        <span class="media-body"> info@company.com </span>
                    </a>
                </div>
                <div class="media">
                    <a href="" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-map-marker-alt tm-contact-icon"></i>
                    </span>
                  </span>
                        <span class="media-body">
                    6120 Suspendisse ultricies<br />Scelerisque tellus, ID
                    10260<br />Magna aliquet porttitor
                  </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-6 px-0">
            <center><h2>Add	a	new	comment</h2></center>

            <div class="tm-contact-form-container">

                <form	action="."	method="post"  class="tm-contact-form">
                    <div class="form-group">
                        {{	comment_form.as_p	}}
                        {%	csrf_token	%}

                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn tm-btn-submit rounded-0">Send</button>
                    </div>
                </form>
                {%	endif	%}

            </div>
        </div>
    </div>
</div>
{%	endblock	%}

templates/blog/post/share.html
{%	extends	"blog/base.html"	%}
{%	block	title	%}Share	a	post{%	endblock	%}
{%	block	content	%}
{%	if	sent	%}
     <section id="section_3" class="tm-section-4">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <div class="tm-section-text-container-7 tm-bg-dark-gray">
                <h2 class="tm-section-title-mb tm-text-primary-bright">
E-mail	successfully	sent
                </h2>
                <hr
                  class="tm-hr-mb tm-hr-primary-bright tm-section-underline ml-0"
                />
                <p>
	"{{	post.title	}}"	was	successfully	sent	to	{{	form.cleaned_data.to	}}.
</p>


              </div>
            </div>
          </div>
        </div>
      </section>

{%	else	%}

<div id="contact" class="tm-section-contact">

	<div class="row tm-contact-section">
		<div class="col-md-6 px-0">
			<div class="tm-bg-white-alpha tm-contact-left">
				<div class="media mb-5">
					<a href="#" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-phone tm-contact-icon tm-phone-icon"></i>
                    </span>

                  </span>
						<span class="media-body"> 010-020-0340 </span>
					</a>
				</div>
				<div class="media mb-5">
					<a href="mailto:" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-envelope tm-contact-icon"></i>
                    </span>
                  </span>
						<span class="media-body"> info@company.com </span>
					</a>
				</div>
				<div class="media">
					<a href="" class="tm-contact-link">
                  <span class="tm-contact-icon-container">
                    <span class="tm-contact-icon-container-inner">
                      <i class="fas fa-map-marker-alt tm-contact-icon"></i>
                    </span>
                  </span>
						<span class="media-body">
                    6120 Suspendisse ultricies<br />Scelerisque tellus, ID
                    10260<br />Magna aliquet porttitor
                  </span>
					</a>
				</div>
			</div>
		</div>
		<div class="col-md-6 px-0">
				<h2 class="tm-section-title">Share	"{{	post.title	}}"	by	e-mail</h2>

			<div class="tm-contact-form-container">

				<form	action="."	method="post"  class="tm-contact-form">
					<div class="form-group">
						{{	form.as_p	}}
						{%	csrf_token	%}

					</div>
					<div class="text-right">
						<button type="submit" class="btn tm-btn-submit rounded-0">Send Email</button>
					</div>
				</form>
				{%	endif	%}

			</div>
		</div></div>
</div>
		{%	endblock %}